# Generated by Django 2.1.2 on 2022-07-19 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamping', models.DateTimeField(verbose_name='打刻日時')),
                ('stamping_type', models.IntegerField(default=0, verbose_name='打刻の種類')),
                ('stamping_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StampingBy', to=settings.AUTH_USER_MODEL, verbose_name='打刻者')),
            ],
        ),
    ]
